# Generated by Django 5.2.7 on 2026-01-03 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_api_app', '0002_product_user_delete_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
