# Generated by Django 5.2.7 on 2025-12-02 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_api_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='products',
        ),
    ]
